service: wild-spots-api
frameworkVersion: '3.40.0'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  memorySize: 1024
  timeout: 29
  # Serverless will automatically create and manage the deployment bucket
  stackTags:
    Environment: ${self:provider.stage}
    Service: ${self:service}
  tags:
    Environment: ${self:provider.stage}
    Service: ${self:service}
  httpApi:
    cors:
      allowedOrigins:
        - 'https://main.ds390r36pvryt.amplifyapp.com'
        - 'http://localhost:5173'
      allowedHeaders:
        - Content-Type
        - Authorization
        - X-Amz-Date
        - X-Api-Key
        - X-Amz-Security-Token
        - X-Amz-User-Agent
      allowedMethods:
        - OPTIONS
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
      allowCredentials: true

  environment:
    NODE_ENV: ${self:provider.stage}
    SECRETS_ID: ${self:service}-${self:provider.stage}/api/secrets

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: 
            - !Sub arn:aws:secretsmanager:${self:provider.region}:${aws:accountId}:secret:${self:service}-${self:provider.stage}/*

functions:
  api:
    handler: src/lambda.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-offline

package:
  patterns:
    - 'node_modules/**'
    - '!node_modules/.bin/**'
    - '!node_modules/.cache/**'
    - '!node_modules/.prisma/**'
    - '!node_modules/.serverless/**'
    - '!node_modules/.vscode/**'
    - '!node_modules/aws-sdk/**'
    - 'node_modules/express/**'
    - 'node_modules/serverless-http/**'
    - 'node_modules/merge-descriptors/**'
    - 'node_modules/accepts/**'
    - 'node_modules/body-parser/**'
    - 'node_modules/bytes/**'
    - 'node_modules/content-type/**'
    - 'node_modules/debug/**'
    - 'node_modules/depd/**'
    - 'node_modules/encodeurl/**'
    - 'node_modules/escape-html/**'
    - 'node_modules/etag/**'
    - 'node_modules/fresh/**'
    - 'node_modules/http-errors/**'
    - 'node_modules/inherits/**'
    - 'node_modules/media-typer/**'
    - 'node_modules/mime-types/**'
    - 'node_modules/mime-db/**'
    - 'node_modules/ms/**'
    - 'node_modules/on-finished/**'
    - 'node_modules/parseurl/**'
    - 'node_modules/path-to-regexp/**'
    - 'node_modules/proxy-addr/**'
    - 'node_modules/qs/**'
    - 'node_modules/range-parser/**'
    - 'node_modules/raw-body/**'
    - 'node_modules/safe-buffer/**'
    - 'node_modules/safer-buffer/**'
    - 'node_modules/send/**'
    - 'node_modules/serve-static/**'
    - 'node_modules/setprototypeof/**'
    - 'node_modules/statuses/**'
    - 'node_modules/toidentifier/**'
    - 'node_modules/type-is/**'
    - 'node_modules/unpipe/**'
    - 'node_modules/utils-merge/**'
    - 'node_modules/vary/**'